on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            echo ${{ vars.REPOSITORY_NAME}} 
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.REPOSITORY_NAME}}:${{ github.ref_name }}-${{ github.run_number }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.REPOSITORY_NAME}}:${{ github.ref_name }}-${{ github.run_number }}

        - name: Deploy Container App with Custom Script
          run: |
            ls -la
            chmod +x my-script.sh ./deploy_container_app.sh
            ./deploy_container_app.sh
          shell: bash
          env:
            REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
            REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            ROBOFLOW_API_KEY: ${{ secrets.ROBOFLOW_API_KEY }}
            CALLER_API_KEY: ${{ secrets.CALLER_API_KEY }}
            CALLER_SECRET_KEY: ${{ secrets.CALLER_SECRET_KEY }}
